#!/usr/bin/env python3
"""Generate Python models from the code-wrapper JSON schema.

This script uses datamodel-code-generator to produce Pydantic models
from the claude-event.v1.schema.json specification. The generated
models are written to src/code_wrapper/models.py.

Run this whenever the schema changes to keep models in sync.
"""

import json
import sys
from pathlib import Path
from io import StringIO

# Try to import datamodel_code_generator
try:
    from datamodel_code_generator.generate import generate, PythonVersion
except ImportError:
    print("Error: datamodel-code-generator not installed", file=sys.stderr)
    print("Install with: pip install datamodel-code-generator", file=sys.stderr)
    sys.exit(1)

# Paths
script_dir = Path(__file__).parent
repo_root = script_dir.parent.parent
schema_path = repo_root / "schemas" / "claude-event.v1.schema.json"
models_path = script_dir.parent / "src" / "code_wrapper" / "models.py"

if not schema_path.exists():
    print(f"Error: Schema file not found at {schema_path}", file=sys.stderr)
    sys.exit(1)

print(f"Generating models from {schema_path}")
print(f"Output: {models_path}")

try:
    # Create output as string buffer first
    output_buffer = StringIO()

    # Generate models using datamodel-code-generator
    generate(
        schema=schema_path,
        output=output_buffer,
        output_model="pydantic_v2",
        snake_case_field=False,
        target_python_version=PythonVersion.PY39,
        use_annotated=False,
        use_union_operator=False,
        use_standard_collections=True,
        base_class="pydantic.BaseModel",
        use_field_serializers=False,
        use_model_rebuild=False,
        collapse_root_models=True,
        enum_members_as_literals=True,
    )

    generated_code = output_buffer.getvalue()

    # Create header with instructions
    header = '''"""Type models for code-wrapper wire protocol events (v1).

Auto-generated from the claude-event.v1.schema.json specification.
All events are Pydantic BaseModel instances, discriminated by the 'type' field.

DO NOT EDIT THIS FILE MANUALLY — run py-code-wrapper/scripts/generate_models.py to regenerate.
"""

from __future__ import annotations

from typing import Any, Literal, Union

from pydantic import BaseModel, Field


'''

    # Start with header
    final_code = header

    # Parse and process the generated code
    lines = generated_code.split('\n')
    skip_imports = True
    for line in lines:
        # Skip initial imports/type imports from generated code
        if skip_imports:
            if line.startswith('from __future__') or line.startswith('from typing') or line.startswith('from pydantic'):
                continue
            if line.strip() and not line.startswith('class '):
                continue
            skip_imports = False

        # Add the processed line
        if line.strip() or not skip_imports:
            final_code += line + '\n'

    # Ensure discriminated union is properly defined
    if 'ClaudeEvent = Union[' not in final_code:
        # Add the union if not present
        final_code += '''

# Discriminated union of all event types
ClaudeEvent = Union[
    TextEvent,
    ThinkingEvent,
    ToolUseEvent,
    ToolResultEvent,
    ProgressEvent,
    ReadyEvent,
    RetryEvent,
    DoneEvent,
    ErrorEvent,
    RawEvent,
]
'''

    # Add deserialization function
    final_code += '''

def deserialize_event(data: dict[str, Any]) -> ClaudeEvent:
    """Deserialize a JSON object into a typed ClaudeEvent.

    Discriminates on the 'type' field. Unknown types become RawEvent.
    Raises ValueError if data is missing required fields for a known type.
    """
    event_type: str = data.get("type", "")

    type_map = {
        "text": TextEvent,
        "thinking": ThinkingEvent,
        "tool_use": ToolUseEvent,
        "tool_result": ToolResultEvent,
        "progress": ProgressEvent,
        "ready": ReadyEvent,
        "retry": RetryEvent,
        "done": DoneEvent,
        "error": ErrorEvent,
        "raw": RawEvent,
    }

    event_class = type_map.get(event_type)
    if event_class:
        return event_class(**data)  # type: ignore[no-any-return]

    # Unknown type → wrap as RawEvent
    return RawEvent(
        v=data.get("v", 1),
        seq=data.get("seq", 0),
        timestamp=data.get("timestamp", 0),
        type="raw",
        rawType=event_type or "unknown",
        rawSubtype=data.get("subtype"),
        data=data,
    )
'''

    models_path.write_text(final_code)
    print(f"✓ Generated models at {models_path}")

except Exception as e:
    print(f"Error generating models: {e}", file=sys.stderr)
    import traceback
    traceback.print_exc()
    sys.exit(1)
