#!/usr/bin/env python3
"""Generate Python models from the code-wrapper JSON schema.

This script uses datamodel-code-generator to produce Pydantic models
from the claude-event.v1.schema.json specification. The generated
models are written to src/code_wrapper/models.py.

Run this whenever the schema changes to keep models in sync.
"""

import contextlib
import io
import json
import sys
from pathlib import Path

# Try to import datamodel_code_generator
try:
    from datamodel_code_generator import (
        DataModelType,
        Formatter,
        InputFileType,
        PythonVersion,
        generate,
    )
    from datamodel_code_generator.parser import LiteralType
except ImportError:
    print("Error: datamodel-code-generator not installed", file=sys.stderr)
    print("Install with: pip install datamodel-code-generator", file=sys.stderr)
    sys.exit(1)

# Paths
script_dir = Path(__file__).parent
repo_root = script_dir.parent.parent
schema_path = repo_root / "schemas" / "claude-event.v1.schema.json"
models_path = script_dir.parent / "src" / "code_wrapper" / "models.py"

if not schema_path.exists():
    print(f"Error: Schema file not found at {schema_path}", file=sys.stderr)
    sys.exit(1)

print(f"Generating models from {schema_path}")
print(f"Output: {models_path}")

try:
    # Load schema and remove remote $id to avoid fetching non-existent URLs
    with open(schema_path, "r") as f:
        schema_dict = json.load(f)

    # Remove the remote $id to avoid ref resolution issues
    if "$id" in schema_dict:
        del schema_dict["$id"]

    # Convert back to JSON string to avoid version-specific issues with dict input
    schema_json = json.dumps(schema_dict)

    # Generate models using datamodel-code-generator.
    # NOTE: as of datamodel-code-generator 0.45.0, generate() always returns
    # None and, when called without `output=`, writes the generated code to
    # stdout instead. Capture that stdout to get the code as a string, since
    # we still need to post-process it below before writing the real output
    # file.
    stdout_capture = io.StringIO()
    with contextlib.redirect_stdout(stdout_capture):
        generate(
            input_=schema_json,
            input_file_type=InputFileType.JsonSchema,
            output_model_type=DataModelType.PydanticV2BaseModel,
            snake_case_field=False,
            target_python_version=PythonVersion.PY_311,
            use_annotated=False,
            use_union_operator=False,
            use_standard_collections=True,
            base_class="pydantic.BaseModel",
            collapse_root_models=True,
            enum_field_as_literal=LiteralType.All,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        )
    generated_code = stdout_capture.getvalue().rstrip("\n")
    if not generated_code.strip():
        raise RuntimeError(
            "datamodel-code-generator produced no output (check schema validity "
            "and installed library version compatibility)"
        )

    # Create header with instructions
    header = '''"""Type models for code-wrapper wire protocol events (v1).

Auto-generated from the claude-event.v1.schema.json specification.
All events are Pydantic BaseModel instances, discriminated by the 'type' field.

DO NOT EDIT THIS FILE MANUALLY — run py-code-wrapper/scripts/generate_models.py to regenerate.
"""

from __future__ import annotations

from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel


'''

    # Start with header
    final_code = header

    # Parse and process the generated code
    lines = generated_code.split("\n")
    skip_imports = True
    for line in lines:
        # Skip all lines until we find the first class definition
        if skip_imports:
            if line.startswith("class "):
                skip_imports = False
            else:
                continue

        # Add all lines after imports
        final_code += line + "\n"

    # Ensure discriminated union is properly defined
    if "ClaudeEvent = Union[" not in final_code:
        # Add the union if not present
        final_code += """

# Discriminated union of all event types
ClaudeEvent = Union[
    TextEvent,
    ThinkingEvent,
    ToolUseEvent,
    ToolResultEvent,
    ProgressEvent,
    ReadyEvent,
    RetryEvent,
    DoneEvent,
    ErrorEvent,
    RawEvent,
]
"""

    # Add deserialization function
    final_code += '''

def deserialize_event(data: dict[str, Any]) -> ClaudeEvent:
    """Deserialize a JSON object into a typed ClaudeEvent.

    Discriminates on the 'type' field. Unknown types become RawEvent.
    Raises ValidationError if data is missing required fields for a known type.
    """
    event_type: str = data.get("type", "")

    type_map = {
        "text": TextEvent,
        "thinking": ThinkingEvent,
        "tool_use": ToolUseEvent,
        "tool_result": ToolResultEvent,
        "progress": ProgressEvent,
        "ready": ReadyEvent,
        "retry": RetryEvent,
        "done": DoneEvent,
        "error": ErrorEvent,
        "raw": RawEvent,
    }

    event_class = type_map.get(event_type)
    if event_class:
        return event_class(**data)  # type: ignore[no-any-return]

    # Unknown type → wrap as RawEvent
    return RawEvent(
        v=data.get("v", 1),
        seq=data.get("seq", 0),
        timestamp=data.get("timestamp", 0),
        type="raw",
        rawType=event_type or "unknown",
        rawSubtype=data.get("subtype"),
        data=data,
    )
'''

    models_path.write_text(final_code)
    print(f"✓ Generated models at {models_path}")

except Exception as e:
    print(f"Error generating models: {e}", file=sys.stderr)
    import traceback

    traceback.print_exc()
    sys.exit(1)
